---
- name: Setup
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Create a 4096-bit SSH key for user {{ user }}
      user:
        name: "{{ user }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
