---
- name: Install udiskie
  package:
    name: udiskie
    state: present

- name: Create Ëœ/.xprofile
  template:
    src: templates/.xprofile
    destination: /home/{{ user }}/.xprofile
    owner: "{{ user }}"
    mode: 0755

- name: Delete default directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /home/{{ user }}/Desktop
  - /home/{{ user }}/Videos
  - /home/{{ user }}/Templates
  - /home/{{ user }}/Public
  - /home/{{ user }}/Pictures
  - /home/{{ user }}/Music
  - /home/{{ user }}/Downloads
  - /home/{{ user }}/Documents
